### ISSUE TITLE
Отлавливание тапа по маркеру

### ISSUE THREAD

**Issue by dentikhomirov** [2gis/native-sdk-ios-demo#156]
- Как отлавливать тап по маркеру или иконке кластера, когда весь проект на UIKit, а не SwiftUI? Из демо-проекта и документации не очень очевидно.
- Нужно ли добавлять к mapView свой UITapGestureRecognizer?

**Comment by ok-gurov** [comment]
Информацию об объекте на карте получаем тем же способом - [Map.getRenderedObjects](https://docs.2gis.com/ru/ios/sdk/examples#nav-lvl1--%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2_%D0%BF%D0%BE_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC_%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%B0%D0%BC).
`UITapGestureRecognizer` будет уместен. Необходимо точку тапа перевести в пиксельные координаты и запросить отображаемые объекты при помощи [getRenderedObjects](https://docs.2gis.com/ru/ios/sdk/reference/2.0/Map#nav-lvl1--getRenderedObjects):
```swift
@objc private func mapViewTapped(_ sender: UITapGestureRecognizer) {
  let tapLocation = sender.location(in: self.mapView)

  let scale = UIScreen.main.nativeScale
  let toMapTransform = CGAffineTransform(scaleX: scale, y: scale)
  let mapLocation = tapLocation.applying(toMapTransform)
  let mapPoint = ScreenPoint(x: Float(mapLocation.x), y: Float(mapLocation.y))

  self.renderedObjectSearchCancellable?.cancel()
  self.renderedObjectSearchCancellable = self.map.getRenderedObjects(centerPoint: mapPoint).sink(
    receiveValue: { objects in
      guard let mapObject = objects.first?.item.item else { return }

      switch mapObject {
        case is SimpleClusterObject:
          print("Cluster")
        case is Marker:
          print("Marker")
        default:
          print("Some object: \(mapObject)")
      }
    },
    failure: { error in
      print(error.localizedDescription)
    }
  )
}
```
Подразумевается, что на mapView добавлен `UITapGestureRecognizer` с селектором `self.mapViewTapped(_:)`.
