### ISSUE TITLE
Cannot find type 'RouteEditor' in scope

### ISSUE THREAD

**Issue by SparklingAir** [2gis/native-sdk-ios-demo#61]
A lot of errors after adding the sdk (https://github.com/2gis/mobile-sdk-map-swift-package) to the project, as described in the readme:

Cannot find type 'RouteEditor' in scope
Cannot find type 'RouteEditorSource' in scope
Cannot find 'RouteSearchPoint' in scope
Cannot find 'RouteOptions' in scope
Cannot find 'RouteParams' in scope
Cannot find type 'TrafficRoute' in scope
Cannot find type 'RouteMapObject' in scope
Cannot find type 'RoutePointMapObject' in scope

**Comment by lagner** [comment]
You mentioned you had changed FullSDK to MapSDK before build. It was wrong. The application works with the full version of SDK only. Changing dependency leads to a broken build.
Therefore to get the demo you should build it as is. Without any changes.

Anyway, we understand it can be confusing. We will remove all features related full version soon.

Thank you for your feedback.
