### ISSUE TITLE
Missing package product 'FullSDK'

### ISSUE THREAD

**Issue by SparklingAir** [2gis/native-sdk-ios-demo#62]
The app doesn't work right out of the box. You need to first delete the 'FullSDK', and only after that you can add the sdk that the readme points to. However, after that, the application still does not start, which is described here https://github.com/2gis/native-sdk-ios-demo/issues/61.

**Comment by ktoto** [comment]
Access to the Full SDK is temporarily restricted.
Please contact your sales manager for credentials.
